plugin:
    name: 'eduzoneco.management::lang.plugin.name'
    description: 'eduzoneco.management::lang.plugin.description'
    author: eduzoneco
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: 'eduzoneco.management::lang.navigation.parent'
        url: /
        icon: icon-book
        sideMenu:
            coursecategory:
                label: 'eduzoneco.management::lang.navigation.coursecategory'
                url: eduzoneco/management/coursecategories
                icon: icon-sitemap
            course:
                label: 'eduzoneco.management::lang.navigation.course'
                url: eduzoneco/management/courses
                icon: icon-puzzle-piece
            Lesson:
                label: Lesson
                url: eduzoneco/management/lessons
                icon: icon-list
