list: $/eduzoneco/management/models/coursecategory/columns.yaml
modelClass: Eduzoneco\Management\Models\CourseCategory
title: CourseCategories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'eduzoneco/management/coursecategories/update/:id'
