# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: Import Users
    modelClass: Eduzoneco\Management\Models\UserImportModel
    list: $/eduzoneco/management/models/userimport/columns.yaml
    redirect: rainlab/user/users

export:
    title: Export Users
    modelClass: Eduzoneco\Management\Models\UserExportModel
    list: $/eduzoneco/management/models/userexport/columns.yaml
    redirect: rainlab/user/users

defaultFormatOptions:
    fileFormat: csv